import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ExternalLink, Award, Brain, BookOpen } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';

interface KnowledgeArticle {
  id: string;
  title: string;
  description: string;
  url: string;
  category: string;
  readTime: string;
  points: number;
  quiz: {
    question: string;
    options: string[];
    correctAnswer: number;
    explanation: string;
  }[];
}

interface KnowledgeBaseProps {
  userProfile: any;
  setUserProfile: React.Dispatch<React.SetStateAction<any>>;
}

const KnowledgeBase: React.FC<KnowledgeBaseProps> = ({ userProfile, setUserProfile }) => {
  const { toast } = useToast();
  const { user } = useAuth();
  const [currentQuiz, setCurrentQuiz] = useState<string | null>(null);
  const [quizAnswers, setQuizAnswers] = useState<{ [key: number]: number }>({});
  const [quizCompleted, setQuizCompleted] = useState<string[]>([]);
  const [showQuizResults, setShowQuizResults] = useState(false);
  const [quizScore, setQuizScore] = useState(0);

  const articles: KnowledgeArticle[] = [
    {
      id: 'heat-pumps',
      title: 'Heat Pumps: A Complete Guide',
      description: 'Everything you need to know about heat pumps, how they work, and their benefits for your home.',
      url: 'https://energysavingtrust.org.uk/advice/heat-pumps/',
      category: 'Energy',
      readTime: '8 min',
      points: 15,
      quiz: [
        {
          question: 'What is the main benefit of a heat pump over traditional heating?',
          options: ['Lower upfront cost', 'Higher efficiency', 'Smaller size', 'No electricity required'],
          correctAnswer: 1,
          explanation: 'Heat pumps are typically 3-4 times more efficient than traditional heating systems.'
        },
        {
          question: 'Which type of heat pump is most common for UK homes?',
          options: ['Ground source', 'Air source', 'Water source', 'Solar source'],
          correctAnswer: 1,
          explanation: 'Air source heat pumps are the most popular choice for UK homes due to easier installation.'
        },
        {
          question: 'Heat pumps work best with which type of heating system?',
          options: ['Radiators only', 'Underfloor heating', 'Fan heaters', 'Storage heaters'],
          correctAnswer: 1,
          explanation: 'Heat pumps work most efficiently with underfloor heating due to lower water temperatures required.'
        },
        {
          question: 'What government support is available for heat pump installation?',
          options: ['No support available', 'Tax relief only', 'Boiler Upgrade Scheme grants', 'Free installation'],
          correctAnswer: 2,
          explanation: 'The UK government offers grants of up to £7,500 through the Boiler Upgrade Scheme.'
        }
      ]
    },
    {
      id: 'solar-panels',
      title: 'Solar Panels Guide',
      description: 'Learn about solar panel technology, costs, savings, and whether they\'re right for your home.',
      url: 'https://energysavingtrust.org.uk/advice/solar-panels/',
      category: 'Energy',
      readTime: '10 min',
      points: 15,
      quiz: [
        {
          question: 'What is the typical payback period for solar panels in the UK?',
          options: ['5-7 years', '10-12 years', '15-20 years', '25+ years'],
          correctAnswer: 1,
          explanation: 'Most solar panel systems pay for themselves within 10-12 years through energy savings.'
        },
        {
          question: 'Which direction should solar panels face for optimal performance in the UK?',
          options: ['North', 'South', 'East', 'West'],
          correctAnswer: 1,
          explanation: 'South-facing panels receive the most sunlight throughout the day in the UK.'
        },
        {
          question: 'What happens to excess electricity generated by solar panels?',
          options: ['It\'s wasted', 'Exported to the grid', 'Stored automatically', 'Powers neighbours\' homes'],
          correctAnswer: 1,
          explanation: 'Excess electricity is exported to the grid, and you can receive payments through the Smart Export Guarantee.'
        },
        {
          question: 'How long do solar panels typically last?',
          options: ['10 years', '15 years', '20 years', '25+ years'],
          correctAnswer: 3,
          explanation: 'Solar panels typically come with 25-year warranties and can last even longer with minimal degradation.'
        }
      ]
    },
    {
      id: 'home-insulation',
      title: 'Home Insulation Guide',
      description: 'Discover how proper insulation can reduce your energy bills and carbon footprint.',
      url: 'https://energysavingtrust.org.uk/advice/insulation/',
      category: 'Buildings',
      readTime: '6 min',
      points: 15,
      quiz: [
        {
          question: 'Which area of the home loses the most heat without proper insulation?',
          options: ['Windows', 'Walls', 'Roof', 'Floor'],
          correctAnswer: 2,
          explanation: 'The roof can account for up to 25% of heat loss in an uninsulated home.'
        },
        {
          question: 'What is the recommended minimum thickness for loft insulation?',
          options: ['100mm', '200mm', '270mm', '350mm'],
          correctAnswer: 2,
          explanation: 'The recommended minimum thickness for loft insulation is 270mm for optimal energy efficiency.'
        },
        {
          question: 'Which type of wall insulation is most common in UK homes?',
          options: ['External wall insulation', 'Cavity wall insulation', 'Internal wall insulation', 'No insulation'],
          correctAnswer: 1,
          explanation: 'Cavity wall insulation is the most common and cost-effective option for UK homes built after 1920.'
        },
        {
          question: 'How much can proper insulation reduce heating bills?',
          options: ['5-10%', '15-25%', '30-50%', '60-70%'],
          correctAnswer: 1,
          explanation: 'Proper insulation can typically reduce heating bills by 15-25% or more.'
        }
      ]
    },
    {
      id: 'electric-vehicles',
      title: 'Electric Vehicle Guide',
      description: 'Everything about electric cars, charging, costs, and environmental benefits.',
      url: 'https://www.gov.uk/plug-in-car-van-grants',
      category: 'Transport',
      readTime: '12 min',
      points: 15,
      quiz: [
        {
          question: 'What is the average range of modern electric vehicles?',
          options: ['100-150 miles', '200-300 miles', '400-500 miles', '600+ miles'],
          correctAnswer: 1,
          explanation: 'Most modern EVs have a range of 200-300 miles on a single charge, suitable for most daily needs.'
        },
        {
          question: 'How much cheaper is charging an EV compared to petrol per mile?',
          options: ['Same cost', '25% cheaper', '50% cheaper', '75% cheaper'],
          correctAnswer: 2,
          explanation: 'Charging an EV typically costs about 50% less per mile compared to petrol or diesel.'
        },
        {
          question: 'What government incentive is available for EV purchases?',
          options: ['No incentives', 'Tax exemption only', 'Plug-in Car Grant', 'Free charging'],
          correctAnswer: 2,
          explanation: 'The UK government offers grants through the Plug-in Car Grant scheme for eligible vehicles.'
        },
        {
          question: 'How long does it take to charge an EV at a rapid charger?',
          options: ['8-12 hours', '4-6 hours', '1-2 hours', '20-45 minutes'],
          correctAnswer: 3,
          explanation: 'Rapid chargers can charge most EVs to 80% capacity in 20-45 minutes.'
        }
      ]
    },
    {
      id: 'thermostat-reduction',
      title: 'Turn Down Your Thermostat: 1 Degree Makes a Difference',
      description: 'Discover the surprising impact of reducing your thermostat by just 1°C on energy bills, carbon emissions, and the environment.',
      url: 'https://energysavingtrust.org.uk/advice/space-heating/',
      category: 'Energy',
      readTime: '5 min',
      points: 20,
      quiz: [
        {
          question: 'How much can turning down your thermostat by 1°C reduce your heating bill?',
          options: ['2-3%', '6-10%', '15-20%', '25-30%'],
          correctAnswer: 1,
          explanation: 'According to the Energy Saving Trust, reducing your thermostat by just 1°C can cut your heating bill by 6-10% - that\'s up to £80 per year for the average home.'
        },
        {
          question: 'How much CO2 can a household save annually by reducing thermostat by 1°C?',
          options: ['50kg CO2', '150kg CO2', '310kg CO2', '500kg CO2'],
          correctAnswer: 2,
          explanation: 'The Carbon Trust estimates that turning down your thermostat by 1°C can save approximately 310kg of CO2 per year - equivalent to the carbon absorbed by 14 tree seedlings grown for 10 years.'
        },
        {
          question: 'What is the optimal temperature range for home heating according to health experts?',
          options: ['16-18°C', '18-21°C', '22-24°C', '24-26°C'],
          correctAnswer: 1,
          explanation: 'The World Health Organization and NHS recommend 18-21°C for living areas and 16-19°C for bedrooms. Many homes are overheated, so reducing by 1°C often brings you closer to the healthy range.'
        },
        {
          question: 'If every UK household reduced their thermostat by 1°C, what would be the equivalent CO2 saving?',
          options: ['Same as 50,000 cars off the road', 'Same as 500,000 cars off the road', 'Same as 1.2 million cars off the road', 'Same as 2 million cars off the road'],
          correctAnswer: 2,
          explanation: 'According to government analysis, if every UK household turned down their thermostat by 1°C, it would save approximately 8.5 million tonnes of CO2 annually - equivalent to taking 1.2 million cars off the road.'
        },
        {
          question: 'Which heating system responds most efficiently to thermostat reduction?',
          options: ['Electric radiators', 'Gas boilers', 'Heat pumps', 'All systems respond equally'],
          correctAnswer: 2,
          explanation: 'Heat pumps are particularly responsive to thermostat changes. Because they work most efficiently at lower temperatures, reducing your thermostat by 1°C can improve their efficiency significantly, leading to even greater savings.'
        },
        {
          question: 'What additional benefit does thermostat reduction have on indoor air quality?',
          options: ['No effect on air quality', 'Reduces humidity and improves air circulation', 'Increases oxygen levels', 'Eliminates all allergens'],
          correctAnswer: 1,
          explanation: 'Lower indoor temperatures reduce humidity levels and encourage better air circulation, which can help prevent mold growth and improve overall indoor air quality. Overheated homes often have stagnant, humid air.'
        }
      ]
    }
  ];

  const handleReadArticle = (article: KnowledgeArticle) => {
    window.open(article.url, '_blank');
    // Small delay to allow user to read, then show quiz option
    setTimeout(() => {
      if (!quizCompleted.includes(article.id)) {
        toast({
          title: "Ready for the quiz?",
          description: "Test your knowledge and earn points!",
        });
      }
    }, 2000);
  };

  const startQuiz = (articleId: string) => {
    setCurrentQuiz(articleId);
    setQuizAnswers({});
    setShowQuizResults(false);
  };

  const answerQuestion = (questionIndex: number, answerIndex: number) => {
    setQuizAnswers(prev => ({
      ...prev,
      [questionIndex]: answerIndex
    }));
  };

  const submitQuiz = async () => {
    if (!user || !currentQuiz) return;

    const article = articles.find(a => a.id === currentQuiz);
    if (!article) return;

    let correctAnswers = 0;
    article.quiz.forEach((question, index) => {
      if (quizAnswers[index] === question.correctAnswer) {
        correctAnswers++;
      }
    });

    const score = Math.round((correctAnswers / article.quiz.length) * 100);
    setQuizScore(score);
    setShowQuizResults(true);

    // Award points if score is 75% or higher
    if (score >= 75 && !quizCompleted.includes(currentQuiz)) {
      try {
        const newTotalPoints = (userProfile?.total_points || 0) + article.points;
        await supabase
          .from('profiles')
          .update({ total_points: newTotalPoints })
          .eq('user_id', user.id);

        setUserProfile(prev => ({
          ...prev,
          total_points: newTotalPoints
        }));

        setQuizCompleted(prev => [...prev, currentQuiz]);

        toast({
          title: "Quiz Completed!",
          description: `You scored ${score}% and earned ${article.points} points!`,
        });
      } catch (error) {
        console.error('Error updating points:', error);
      }
    } else if (score < 75) {
      toast({
        title: "Quiz Complete",
        description: `You scored ${score}%. You need 75% or higher to earn points. Try again!`,
        variant: "destructive"
      });
    } else {
      toast({
        title: "Already Completed",
        description: "You've already earned points for this quiz!",
      });
    }
  };

  const closeQuiz = () => {
    setCurrentQuiz(null);
    setQuizAnswers({});
    setShowQuizResults(false);
  };

  const canTakeQuiz = (articleId: string) => {
    return Object.keys(quizAnswers).length === articles.find(a => a.id === articleId)?.quiz.length;
  };

  if (currentQuiz) {
    const article = articles.find(a => a.id === currentQuiz);
    if (!article) return null;

    return (
      <Card className="bg-slate-800/50 backdrop-blur-sm border-slate-700">
        <CardHeader>
          <CardTitle className="text-white flex items-center gap-2">
            <Brain className="w-5 h-5" />
            Quiz: {article.title}
          </CardTitle>
          <CardDescription className="text-slate-400">
            Answer all questions to earn {article.points} points (75% required)
          </CardDescription>
        </CardHeader>
        <CardContent>
          {!showQuizResults ? (
            <div className="space-y-6">
              {article.quiz.map((question, qIndex) => (
                <div key={qIndex} className="space-y-3">
                  <h3 className="text-white font-medium">
                    {qIndex + 1}. {question.question}
                  </h3>
                  <div className="space-y-2">
                    {question.options.map((option, oIndex) => (
                      <Button
                        key={oIndex}
                        variant="outline"
                        className={`w-full text-left justify-start ${
                          quizAnswers[qIndex] === oIndex
                            ? 'bg-blue-900/50 border-blue-600 text-blue-300'
                            : 'bg-slate-700/50 border-slate-600 hover:bg-slate-600/50 text-white'
                        }`}
                        onClick={() => answerQuestion(qIndex, oIndex)}
                      >
                        {option}
                      </Button>
                    ))}
                  </div>
                </div>
              ))}

              <div className="flex gap-4 pt-4">
                <Button
                  onClick={submitQuiz}
                  disabled={!canTakeQuiz(currentQuiz)}
                  className="bg-green-600 hover:bg-green-700 text-white"
                >
                  Submit Quiz
                </Button>
                <Button variant="outline" onClick={closeQuiz}>
                  Cancel
                </Button>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="text-center py-6">
                <div className="text-4xl mb-4">
                  {quizScore >= 75 ? '🎉' : '📚'}
                </div>
                <h3 className="text-xl font-semibold text-white mb-2">
                  You scored {quizScore}%!
                </h3>
                <p className="text-slate-400">
                  {quizScore >= 75 
                    ? `Excellent! You earned ${article.points} points.`
                    : 'Keep learning and try again to earn points!'
                  }
                </p>
              </div>

              <div className="space-y-4">
                <h4 className="text-white font-medium">Quiz Review:</h4>
                {article.quiz.map((question, qIndex) => {
                  const userAnswer = quizAnswers[qIndex];
                  const isCorrect = userAnswer === question.correctAnswer;
                  
                  return (
                    <div key={qIndex} className="space-y-2">
                      <p className="text-white text-sm">
                        {qIndex + 1}. {question.question}
                      </p>
                      <div className="pl-4 space-y-1">
                        <p className={`text-sm ${isCorrect ? 'text-green-400' : 'text-red-400'}`}>
                          Your answer: {question.options[userAnswer]} {isCorrect ? '✓' : '✗'}
                        </p>
                        {!isCorrect && (
                          <p className="text-green-400 text-sm">
                            Correct: {question.options[question.correctAnswer]}
                          </p>
                        )}
                        <p className="text-slate-400 text-xs">
                          {question.explanation}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>

              <Button onClick={closeQuiz} className="w-full">
                Back to Knowledge Base
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="bg-slate-800/50 backdrop-blur-sm border-slate-700">
      <CardHeader>
        <CardTitle className="text-white flex items-center gap-2">
          <BookOpen className="w-5 h-5" />
          Knowledge Base
        </CardTitle>
        <CardDescription className="text-slate-200">
          Read articles and take quizzes to earn points for the tech shop
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {articles.map((article) => {
            const isCompleted = quizCompleted.includes(article.id);
            
            return (
              <div key={article.id} className="space-y-4">
                <div className="p-4 rounded-lg border bg-slate-700/50 border-slate-600">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary">{article.category}</Badge>
                      <Badge variant="outline" className="text-xs">
                        {article.readTime}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-1">
                      <Award className="w-4 h-4 text-yellow-400" />
                      <span className="text-sm text-yellow-400">{article.points}pts</span>
                    </div>
                  </div>
                  
                  <h3 className="font-semibold text-white mb-2">{article.title}</h3>
                  <p className="text-sm text-slate-400 mb-4">{article.description}</p>
                  
                  <div className="flex flex-col gap-2">
                    <Button
                      variant="outline"
                      onClick={() => handleReadArticle(article)}
                      className="bg-slate-600/50 border-slate-500 hover:bg-slate-500/50 text-white"
                    >
                      <ExternalLink className="w-4 h-4 mr-2" />
                      Read Article
                    </Button>
                    
                    <Button
                      onClick={() => startQuiz(article.id)}
                      disabled={isCompleted}
                      className={`${
                        isCompleted 
                          ? 'bg-green-900/30 border-green-700 text-green-300' 
                          : 'bg-blue-600 hover:bg-blue-700 text-white'
                      }`}
                    >
                      <Brain className="w-4 h-4 mr-2" />
                      {isCompleted ? 'Quiz Completed ✓' : 'Take Quiz'}
                    </Button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <div className="mt-6 p-4 bg-blue-900/20 border border-blue-700/30 rounded-lg">
          <h4 className="text-sm font-medium text-blue-300 mb-2">💡 How It Works</h4>
          <ul className="text-xs text-blue-200 space-y-1">
            <li>• Read articles from trusted sources like Energy Saving Trust</li>
            <li>• Take a 4-question quiz after reading each article</li>
            <li>• Score 75% or higher to earn {articles[0]?.points} points</li>
            <li>• Use points to purchase renewable technologies in the Tech Shop</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  );
};

export default KnowledgeBase;