// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var API_BASE = "https://caerphilly-api.onrender.com";
var get_leaderboard_default = defineTool({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Fetch the top residents on the sustainability leaderboard, ranked by total points earned.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(10).describe("Maximum number of entries to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const res = await fetch(`${API_BASE}/leaderboard`);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Leaderboard fetch failed: ${res.status}` }],
        isError: true
      };
    }
    const data = await res.json();
    const rows = Array.isArray(data) ? data : [];
    const top = rows.slice().sort((a, b) => (b.total_points || 0) - (a.total_points || 0)).slice(0, limit).map((r, i) => ({
      rank: i + 1,
      name: r.display_name ?? r.username ?? "Anonymous",
      total_points: r.total_points ?? 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(top, null, 2) }],
      structuredContent: { leaderboard: top }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var API_BASE2 = "https://caerphilly-api.onrender.com";
var get_profile_default = defineTool2({
  name: "get_profile",
  title: "Get resident profile",
  description: "Fetch a resident's public sustainability profile summary (points, carbon footprint, display name) by user ID.",
  inputSchema: {
    user_id: z2.string().min(1).describe("The resident's user ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ user_id }) => {
    const res = await fetch(`${API_BASE2}/profile?user_id=${encodeURIComponent(user_id)}`);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Profile fetch failed: ${res.status}` }],
        isError: true
      };
    }
    const p = await res.json();
    const summary = {
      display_name: p?.display_name ?? p?.username ?? null,
      total_points: p?.total_points ?? 0,
      current_footprint: p?.current_footprint ?? 0,
      member_since: p?.created_at ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "caerphilly-eco-mcp",
  title: "Caerphilly Eco Trail MCP",
  version: "0.1.0",
  instructions: "Tools for the Caerphilly resident sustainability app. Use `get_leaderboard` to see top residents by points, and `get_profile` to look up a resident's public sustainability summary by user ID.",
  tools: [get_leaderboard_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
