// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbxrmrfpjsftmgwuhaym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFieHJtcmZwanNmdG1nd3VoYXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njg5MTEsImV4cCI6MjA2OTU0NDkxMX0.igfFNP8IMN40KrimZkYTrRlx2kNPHguF-JMKW40vh7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});